### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by normaldotcom** [HubertD/cangaroo#9]
Any chance you could post a binary release for Windows? I'm having some trouble getting the source code to build. Thanks!

**Comment by rusefillc** [comment]
There is http://canable.io/utilities/cangaroo-win32-b4a9d6d.zip

PS: is this whole repo more or less dead?

**Comment by normaldotcom** [comment]
Haven't seen movement on this repo in a while, but I do have a fork with transmit support and plan on hopefully adding some additional features as time allows: https://github.com/normaldotcom/cangaroo/ (the binary at your link above is built from this repo).
